### ISSUE TITLE
Course Reviews Page

### ISSUE THREAD

**Issue by chinathaip** [stamford-syntax-club/course-compose#40]
## Overview
This is a page to see the reviews of each course

### Design:  @NayHtetKyaw 
 https://www.figma.com/file/PXPMF9wEKCCGy8x1t0DVPJ/Course-Compose?type=design&node-id=0%3A1&mode=design&t=2XR2zFkFSFyocduy-1

### Frontend - @NayHtetKyaw 
- [x] Display course details
- [x] Display course reviews:
  - sends a `GET` request to `/api/courses/:courseCode/reviews?pageSize=10&pageNumber=1`
     - if user is logged in, attach the JWT in the request header (Bearer)
     - user's own review will contain a field `"isOwner": true`. It will be, if there is any, located at the first element of the array
  - users who are not logged in, or never wrote any reviews before will be limited to view only 2 reviews per course
     - in this case you should display some message box to inform users about this as well as encourage them to start writing reviews
- [x] Submit new review
  - only logged in users can submit new reviews
  - sends a `POST` request to `/api/courses/:courseCode/reviews` along with the JWT in the request header (Bearer)
     - as well as the following request body
       ```json
            {
               "academic_year": 2023,
               "description": "This course is good......",
               "rating": 2
            }
       ```

### DTO
```json
// GET /api/courses/ITE221/reviews?pageNumber=1&pageSize=10
{
    "pageInformation": {
        "number": 1,
        "size": 10
    },
    "totalNumberOfItems": 2,
    "totalPages": 1,
    "data": [
                 {
                     "id": 5,
                     "academicYear": 2022,
                     "description": "Some review for ITE221!",
                     "rating": 2,
                     "isOwner": true,
                     "status": "APPROVED",
                     "votes": 5,
                     "course": {
                           "id": 2,
                           "code": "ITE221"
                     },
                     "profile": {
                           "id": "d5a59cb2-1f22-4e23-8ef0-7108e54f842b"
                     },
                     "created_at": "2023-11-23T14:00:00Z"
                 },
                 {
                     "id": 9,
                     "academicYear": 2022,
                     "description": "Some review for ITE442",
                     "rating": 2,
                     "status": "APPROVED",
                     "votes": 0,
                     "course": {
                           "id": 2,
                           "code": "ITE221"
                     },
                     "profile": {
                           "id": "j2a59cb2-1f22-4e23-8ef0-7108e54f849s"
                     },
                     "created_at": "2023-11-23T14:00:00Z"
                 }
     ]
}
```

**Comment by NayHtetKyaw** [comment]
I'll try my  best !

**Comment by chinathaip** [comment]
> I'll try my  best !

Yessirr, let's start by creating the UI and display some course detail + reviews🔥

**Comment by chinathaip** [comment]
https://github.com/stamford-syntax-club/course-compose/pull/53
